#!/bin/sh

echo "Atualizando os Plugins do Vim"

cd ~/.vim/pack/plugin/start
git pull https://github.com/cohama/agit.vim.git
git pull https://github.com/dense-analysis/ale.git
git pull https://github.com/jiangmiao/auto-pairs.git
git pull https://github.com/rafi/awesome-vim-colorschemes.git
git pull https://github.com/lilydjwg/colorizer.git
git pull https://github.com/kien/ctrlp.vim.git
git pull https://github.com/mattn/emmet-vim.git
git pull https://github.com/Yggdroot/indentLine.git
git pull https://github.com/preservim/nerdcommenter.git
git pull https://github.com/preservim/nerdtree.git
git pull https://github.com/Xuyuanp/nerdtree-git-plugin.git
git pull https://github.com/vim-airline/vim-airline.git
git pull https://github.com/vim-airline/vim-airline-themes.git
git pull https://github.com/alvan/vim-closetag.git
git pull https://github.com/tomasiser/vim-code-dark.git
git pull https://github.com/flazz/vim-colorschemes.git
git pull https://github.com/ryanoasis/vim-devicons.git
git pull https://github.com/sheerun/vim-polyglot.git

cd
cd ~/.vim/pack/plugin/opt
git pull https://github.com/rstacruz/vim-closer.git
git pull https://github.com/zeekay/vim-beautify.git
git pull https://github.com/tpope/vim-endwise.git

echo "Atualização concluida"
